version: 2

updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
    open-pull-requests-limit: 30
    groups:
      polkadot:
        applies-to: version-updates
        dependency-type: "production"
        patterns:
        - "@polkadot*"
        update-types:
        - "major"
        - "minor"
        - "patch"

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
